name: Environment Status

on:
  workflow_dispatch: {}

permissions:
  deployments: write

jobs:
  render:
    uses: Solierrr/.github/.github/workflows/environment-status.yml@main
    with:
      environment: ALIVE
      check: http
      url: https://web-sandbox-7ug0.onrender.com
